plugins {
    id 'java'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '4.3.2'
}

group 'co.com.parabank'
version '1.0-SNAPSHOT'

ext {
    serenityVersion = '4.3.4'
    cucumberVersion = '7.31.0'
    lombokVersion = '1.18.30'
    fakerVersion = '1.0.2'
    assertj_core_version="3.23.1"
}

repositories {
    mavenCentral()
}

dependencies {

    implementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-junit:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    implementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    implementation "org.assertj:assertj-core:${assertj_core_version}"


    testImplementation "io.cucumber:cucumber-java:${cucumberVersion}"
    testImplementation "io.cucumber:cucumber-junit:${cucumberVersion}"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    implementation "com.github.javafaker:javafaker:${fakerVersion}"
}

test {
    def parameter = '-Denvironment='
    def environment = System.getProperty("environment")
    jvmArgs(parameter + environment)

    testLogging {
        events "passed", "skipped", "failed", "standard_out", "standard_error"
        showStandardStreams = true
        exceptionFormat = "full"
    }

    finalizedBy(aggregate)
}